name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-web-app:latest .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      run: |
        docker tag my-web-app:latest 313518852467.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
        docker push 313518852467.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
